#!/usr/local/bin/node

let fs = require('fs');

let Phrase = require('./index.js');

let text = fs.readFileSync('phrases.txt', 'utf-8');

let palindromes = text.split('\n').map(line => {
  let phrase = new Phrase(line);
  if (phrase.palindrome()) {
    console.log(`palindrome detected: ${line}`);
  }
}).join('\n');

fs.writeFileSync('palindromes.txt', palindromes);
