#!/usr/local/bin/node

let fs = require('fs');
let Phrase = require('AshNaz87-palindrome');

let text = fs.readFileSync('phrases.txt', 'utf-8');
text.split('\n').forEach(function(line) {
  let phrase = new Phrase(line);
})